name: 'Setup Docker Compose'
description: 'An action to setup docker compose environment within GitHub Actions.'
inputs:
  file:
    description: 'the file to parse targets from, normally compose.yml. supported extentions: yml, json'
    required: true
  cache-key:
    description: 'the cache key to use for saving build data. defaults to "default"'
    required: false
    default: 'default'
  registry:
    description: 'whether to use a local registry or not. defaults to false'
    required: false
    default: false
  localhost:
    description: 'whether to replace targets registry to localhost or not. registry must be true to use this. defaults to false'
    required: false
    default: false
  pull:
    description: 'whether to pull targets images. defaults to false'
    required: false
    default: false
  pull-opts:
    description: 'options to pass to docker compose pull. pull must be true to use this. defaults to ""'
    required: false
    default: ""
  bake:
    description: 'whether to bake targets. defaults to false'
    required: false
    default: false
  push:
    description: 'whether to push targets images after baking. bake must be true to use this. defaults to false'
    required: false
    default: false
  bake-opts:
    description: 'options to pass to docker buildx bake. bake must be true to use this. defaults to ""'
    required: false
    default: ""
  up:
    description: 'whether to boot up docker compose. defaults to true'
    required: false
    default: true
  up-opts:
    description: 'options to pass to docker compose up. up must be true to use this. defaults to "-d"'
    required: false
    default: "-d"
  dry-run:
    description: '[debugging] dry-run the action'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - if: inputs.bake
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ inputs.cache-key }}-buildx-cache-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-key }}-buildx-cache-${{ github.ref }}
          ${{ inputs.cache-key }}-buildx-cache-
    - if: inputs.bake
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - if: inputs.registry
      uses: actions/cache@v3
      with:
        path: /tmp/docker-registry
        key: ${{ inputs.cache-key }}-docker-registry-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-key }}-docker-registry-${{ github.ref }}
          ${{ inputs.cache-key }}-docker-registry-
    - if: inputs.registry
      shell: bash
      run: |
        [ "${{ inputs.dry-run }}" = "true" ]&&prefix="echo"; \
        $prefix docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2; \
        $prefix npx wait-on tcp:5000
    - if: inputs.localhost
      id: localhost
      shell: bash
      run: |
        [ "${{ inputs.dry-run }}" = "true" ]&&prefix="echo"; \
        $prefix echo TODO: localhost conversion
    - if: inputs.pull
      shell: bash
      run: |
        [ "${{ inputs.dry-run }}" = "true" ]&&prefix="echo"; \
        $prefix docker compose -f "${{ inputs.file }}" pull ${{ inputs.pull-opts }}
    - if: inputs.bake
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        [ "${{ inputs.dry-run }}" = "true" ]&&prefix="echo"; \
        [ "${{ inputs.push }}" = "true" ]&&action="--push"||action="--load"; \
        $prefix docker buildx bake \
            --builder="${{ steps.buildx.outputs.name }}" \
            --set='*.cache-from=type=local,src=/tmp/.buildx-cache' \
            --set='*.cache-to=type=local,dest=/tmp/.buildx-cache' \
            $action \
            -f "${{ inputs.file }}" ${{ inputs.bake-opts }}
    - if: inputs.up
      shell: bash
      run: |
        [ "${{ inputs.dry-run }}" = "true" ]&&prefix="echo"; \
        $prefix docker compose -f "${{ inputs.file }}" up ${{ inputs.up-opts }}
