# see examples/pull-and-bake.yml/.github/main.yml
name: Pull and Bake

# Controls when the workflow will run
on:
  workflow_call:
    inputs: { }
    secrets: { }
env:
  COMPOSE_FILE: examples/pull-and-bake/compose.yml
jobs:
  pull-and-bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: ./
        with:
          file: ${{ env.COMPOSE_FILE }}
          cache-key: pull-and-bake
          pull: true
          bake: true
      - name: Check Batch Runner
        run: docker compose -f ${{ env.COMPOSE_FILE }} exec my-runner bash -c 'cat <(curl -s echo:5678) /the_message'
