# see examples/share-image-with-cache/.github/main.yml
name: Share Image with Cache

# Controls when the workflow will run
on:
  workflow_call:
    inputs: { }
    secrets: { }
env:
  COMPOSE_FILE: examples/share-image-with-cache/compose.yml
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker Compose
        uses: ./
        with:
          file: ${{ env.COMPOSE_FILE }}
          cache-key: share-image-with-cache
          shared: true
          bake: true
          push: true
  use_image:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: ./
        with:
          file: ${{ env.COMPOSE_FILE }}
          cache-key: share-image-with-cache
          shared: true
          pull: true
      - name: Check Batch Runner
        run: docker compose -f ${{ env.COMPOSE_FILE }} exec my-runner bash -c 'cat <(curl -s echo:5678) /the_message'
