name: Simple Docker Compose

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
jobs:
  test_batch_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: ./
        with:
          file: simple-docker-compose/compose.yml
      - name: Check Batch Runner
        run: docker compose exec batch-runner bash -c 'echo Hello, World'
